### ISSUE TITLE
filter-by with value omitted isn't working

### ISSUE THREAD

**Issue by henrymazza** [DockYard/ember-composable-helpers#98]
` {{#each (filter-by 'hasDirtyAttributes' true model) as |m|}}`

works but not

` {{#each (filter-by 'hasDirtyAttributes' model) as |m|}}`

**Comment by martndemus** [comment]
Fixed in #112

**Comment by leizhao4** [comment]
#112 fixed a different bug but not this one. This bug still exist.
